version: '3'

services:
  django:
    build: ./django_app
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django

  ingress:
    build: ./ingress
    ports:
      - "443:443"
    depends_on:
      - django
